# .circleci/config.yml
version: 2
jobs:
  hello-world:
    steps:
      - checkout
      - run:
          command: echo 'Hello World !!'

workflows:
  version: 2
  hello-world:
    jobs:
      - hello-world
