# .circleci/config.yml
version: 2
jobs:
  notification:
    macos:
      xcode: "10.0.0"
    working_directory: /Users/distiller/project
    environment:
      FL_OUTPUT_DIR: output
      
    steps:
      - checkout
      - run:
          name: notification Slack
          command: fastlane SlackTest

workflows:
  version: 2
  build-and-test:
    jobs:
      - notification

