# .circleci/config.yml
version: 2
jobs:
  notification-job:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run:
          command: fastlane SlackTest

workflows:
  version: 2
  notification-workflow:
    jobs:
      - notification-job
