# .circleci/config.yml
version: 2
jobs:
  notification:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run:
          command: fastlane slackTest

  runTest:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run:
          command: fastlane RunTest


workflows:
  version: 2
  notification:
    jobs:
      - notification
  runTest:
    jobs:
      - runTest
