# .circleci/config.yml
version: 2
jobs:
  runTest:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run:
          command: 
            fastlane runTest

  screenshot:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout
      - run:
          command: 
            fastlane snapshot update
            fastlane screenshots

workflows:
  version: 2
  runTest:
    jobs:
      - runTest

  screenshot:
    jobs:
      - screenshot

