# .circleci/config.yml
version: 2
jobs:
  notification:
    steps:
      - checkout
      - run:
          name: notification Slack
          command: fastlane SlackTest

workflows:
  version: 2
  notification-workflow:
    jobs:
      - notification
