# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    ENV["SLACK_URL"] = 'https://hooks.slack.com/services/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'
  end

  desc "Description of what the lane does"
  lane :slackTest do
    slack(
       message: 'Slack Test !!'
   )
  end

  desc "Run the test"
  lane :runTest do
    scan(scheme: "CircleCITest")
  end

end
