default_platform(:ios)

platform :ios do

  before_all do
    ENV["SLACK_URL"] = 'https://hooks.slack.com/services/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'
  end

  desc "Send a success/error message to your Slack group"
  lane :slackTest do
    slack(
       message: 'Slack Test !!'
   )
  end

  desc "Run the test"
  lane :runTest do
    scan(scheme: "CircleCITest")
  end

  desc "Screenshot"
  lane :screenshots do
    ENV['FASTLANE_EXPLICIT_OPEN_SIMULATOR'] = '2'
    capture_screenshots
  end

end
